### ISSUE TITLE
Custom Cursor

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/io-game#40]
### Describe the feature you want added:
Cursor RPG Art?

**Comment by steviegt6** [comment]
What kind of style are we going for?

**Comment by valkyrienyanko** [comment]
Anything will go for now.

**Comment by steviegt6** [comment]
Alright. What size should it be? (In pixels.)

**Comment by valkyrienyanko** [comment]
I don't know much about cursors, use your own discretion.

**Comment by steviegt6** [comment]
Okay.

**Comment by steviegt6** [comment]
![Untitled](https://user-images.githubusercontent.com/27323911/67734938-bc9d3580-f9bf-11e9-933b-275b92ce5456.png)
Will this do?

**Comment by steviegt6** [comment]
(It's hard to see cause it's white)

**Comment by steviegt6** [comment]
https://user-images.githubusercontent.com/27323911/67734938-bc9d3580-f9bf-11e9-933b-275b92ce5456.png

**Comment by valkyrienyanko** [comment]
I've tried both p5.js cursor function and the traditional CSS way and neither way work for custom cursors. Nothing is showing up, but when I do something like `cursor: move;` it works.

```css
#defaultCanvas0 { /* p5.js Canvas */
  position: absolute; top: 0; right: 0; left: 0; bottom: 0;
  cursor: url(../assets/test.png);
}
```
